  fixing ExternalChangesToVcs.testSynchronizingToVcs() CommonLVCS._init() catches Throwable, not Exception  