  PY-19877 NPE after getting an exception on creating Python console process fixed  