  fixed PY-4832 Test runner can't attach to pinax django tests  