  fixed emptiness of exception in PyPackageManager on finished() action  