  fixed connection error in ipython v 4  