  fixed PY-12313 Incorrect __file__ value when running tests in a folder on Windows  