  "testFinished" added after "testError" and "testIngore" to fix PY-16314 and PY-16313  