  fix misunderstanding of PyExternalProcessException (EA-40942 - UOE: PyPackageManagerImpl.getPackagesFast)  